### ISSUE TITLE
Missing requirements.txt

### ISSUE THREAD

**Issue by scivision** [ec500-software-engineering/exercise-1-modularity-WenjieLuo2333#1]
We can't build this without requirements.txt since it uses libraries not built-in to Python

**Comment by WenjieLuo2333** [comment]
Ok, i ll upload it.

**Comment by WenjieLuo2333** [comment]
> We can't build this without requirements.txt since it uses libraries not built-in to Python

Please check if it works now and please tell me if there're other problems.
By the way, do I have to include random into requirements.txt?

**Comment by scivision** [comment]
`random` is built into Python, so it's not in requirements.txt
